### ISSUE TITLE
Left side of transferred borders is glitched out

### ISSUE THREAD

**Issue by Difegue** [Difegue/gblnk#1]
![benis2](https://cloud.githubusercontent.com/assets/8237712/3711986/d04b1552-14f5-11e4-949c-8df28f863b39.jpg)
Like so. The actual picture in the center is still rendered pixel-perfect.

This is an issue in the camera cable transferring code written by Chris in 2002. As I haven't fully understood how the cable functions yet, I am currently unable to fix this problem.

**Comment by LysolPionex** [comment]
I'd love to help with this, if I could get my hands on a mad catz cable.  Any ideas?

**Comment by Difegue** [comment]
I got mine on ebay a good 4 years ago. 
They seem way more difficult to find nowadays, but I did find [that one](http://www.ebay.com/itm/PRODUIT-RARE-KIT-CAMERA-LINK-POUR-GAME-BOY-COLOR-POCKET-ET-PC-COMPLET-NEUF-/381951204970?hash=item58ee10de6a:g:Bj0AAOSwA3dYH0KV).

There's also a known schematic of the cable [here](http://www.devrs.com/gb/files/camlink.gif), but it's pretty useless due to no-one having the program to insert into the PIC.

**Comment by LysolPionex** [comment]
Oh wow, thanks!

**Comment by LysolPionex** [comment]
Well, do you need the program if you're just running the gblnk program? I'm running it on Linux, and haven't quite gotten it working yet, and I'm guessing it's that my cable isn't the mad catz one.

**Comment by Difegue** [comment]
I've never tried the program with another cable than the madcatz one, so I wouldn't know.
The binary in the repo is a bit old, you might want to try building it from source.

If you have already done so, where does it bug out?

**Comment by LysolPionex** [comment]
Lol, well my machine is pretty old too. 
I'll try building it locally and see what I get. 

Currently it's failing at one of the two places where it prints out "Timeout while resetting the parallel port".  I already made sure I'm in the group that can access the port, running as sudo.

I honestly only started working in it last night, and already I know the cable needs a resistor that I didn't put in (hoping that note about it not being necessary would prove true).

I'll mess with it some more tonight or tomorrow.  I enjoy a good project.

**Comment by Difegue** [comment]
Well, even if the cable was different, it'd bug out at the part which uses the weird madcatz cable-specific offsets, not at the timeouts, I think.

Good luck!

**Comment by LysolPionex** [comment]
Okay,  that's a good sign at least. 

Thanks!

**Comment by Difegue** [comment]
I've recently helped the [uCON64](http://ucon64.sourceforge.net/) main developer with porting gblnk to uCON64 and improving the processing code. 

uCON64 now does flawless conversions of gameboy printer data to .BMP, including data dumped from the madcatz cable (which it also supports).

I won't be backporting those changes to gblnk as uCON is a way sturdier program, and people should just use it instead! 🎉
